### ISSUE TITLE
Multi-pallet is not showing.

### ISSUE THREAD

**Issue by RaidenRipper** [marco-calautti/Rainbow#11]
Please can you tell me why your program can't read the multi-pallet of this file.

[lic_b_8_c.zip](https://github.com/marco-calautti/Rainbow/files/2799476/lic_b_8_c.zip)

**Comment by marco-calautti** [comment]
Can you tell me if Rainbow has issues only with this file? Or it does not work also with others?

**Comment by marco-calautti** [comment]
I checked the file, and it seems to not follow the right TIM2 standard. For the time being, if your to make it work, just open the tm2 with a hex editor and go to offset 0xE and change the 0003 to 0001.

**Comment by RaidenRipper** [comment]
I have others files here and the same happens, Rainbow don't show the multi-pallets!.

**Comment by RaidenRipper** [comment]
Thank for the info!.
