### ISSUE TITLE
Save Palettes as .cl2

### ISSUE THREAD

**Issue by RaidenRipper** [marco-calautti/Rainbow#13]
I would to ask if you can make the program save the pallets as .cl2?.
Sorry for posting a request here.

**Comment by marco-calautti** [comment]
Actually, I do not even know what a .cl2 file looks like. What is that?

**Comment by RaidenRipper** [comment]
Inside this 7zip file will found the .tm2 image and the pallet in cl2 format!.

**Comment by marco-calautti** [comment]
If you just want to apply the palette to the grayscale image, you can use ImageMagick's convert command.

` convert gray_image.png output_colored_image.png -clut palette.png`

**Comment by marco-calautti** [comment]
Whic 7zip file?

**Comment by RaidenRipper** [comment]
Sorry, the GitHub seems not to uploaded the file.
Here: https://mega.nz/#!jpczGIzT!_85J5t3-Q01AKixlusISDuMqeYBFAFTsod-4yl_nq0E

**Comment by marco-calautti** [comment]
As I said, you can easily apply the palette to the grayscale image via the command line, and using the convert command of ImageMagick:

`convert gray_image.png palette.png -clut output_colored_image.png`

**Comment by marco-calautti** [comment]
If you want to keep the transparency of the palette, then you can use the command:

`convert -alpha Off image_grayscale.png -channel RGBA palette.png -clut image_colored.png`

This is the result with your tm2 file:
[out.png](https://postimg.cc/vcYNrQnD)

**Comment by marco-calautti** [comment]
If you want to remove the alpha, but you don't want to make fully transparent colors show, after you apply the palette, you can run the command:
`convert image_colored_with_alpha.png -channel Alpha -evaluate Multiply 2 output.png`

you can replace the "2" with whatever amount you want to make the image less transparent.

As you can see, you do not need any .cI2 file to work with multipalette images.

**Comment by RaidenRipper** [comment]
Thanks!

**Comment by RaidenRipper** [comment]
Did you know if is possible to edit this images with new colors?.

**Comment by marco-calautti** [comment]
You just have to do the reverse. Modify the colored image, and extract the
palette with imagemagick.

You can find a lot of tutorials for that online.

Il lun 11 mar 2019, 21:58 RaidenRipper <notifications@github.com> ha
scritto:

**Comment by RaidenRipper** [comment]
Can you tell me white my images are all resulting in a background black and not like yours?.

**Comment by marco-calautti** [comment]
You have to keep the transparency of the palette, when applying it to the grayscale image:
`convert -alpha Off image_grayscale.png -channel RGBA palette.png -clut image_colored.png`
