### ISSUE TITLE
PaRappa the Rapper 2 TIM2 .tm0 textures come as a scrambled mess

### ISSUE THREAD

**Issue by oddMLan** [marco-calautti/Rainbow#3]
Hello. When I try to open any .tm0 texture this is the result:
![parappascrambledtm0](https://cloud.githubusercontent.com/assets/7278372/6520294/8847cf68-c380-11e4-9156-a136bc419008.png)
And I'm pretty sure it's not supposed to be like that ;)

However, it can open .tm1 and .tm2 textures just fine.
![parappastm1](https://cloud.githubusercontent.com/assets/7278372/6520295/8b52dd42-c380-11e4-8a84-85666f1aea7a.png)
![parappastm2](https://cloud.githubusercontent.com/assets/7278372/6520296/8cae8420-c380-11e4-95f1-b5660696aeac.png)

I tried the official OptiX iMage Studio to open the textures; tm1 and tm2 show up just fine but with tm0 I get the same result as above. So tm0 might be a slightly different format.

I found out that the PaRappa The Rapper 2 proto executable inside the Japanese McDonald's Happy Disc has A LOT of debug info in it (which the retail version doesn't have), including some info about the TIM2 format variant used in the game (the .tm1 and .tm0 seem to be some sort of palleted textures) and possibly even more.

I attached the proto ELF file. Just open an Hex editor and look up for all the "TIM2" references. I also attached a folder full of .tm0 and .tm1 textures directly extracted from the game's archives.
https://www.dropbox.com/s/m5pc1zkfi4rsusr/PTR_Proto_data.rar?dl=0

Hope this to be of any help. Also thanks for making this nifty tool!

**Comment by marco-calautti** [comment]
Mmmm, by looking at the pixels in the first screenshot, I suppose the tm0 images are dummy images, not used by the game. I will investigate by the way. Did you try to change these images and see what happens in game?

**Comment by oddMLan** [comment]
Hello again, sorry for the delay

NOTE: The game stores all the textures inside compressed archives (INT files) which can be extracted using QuickBMS + this script: http://aluigi.altervista.org/papers/bms/others/parappa_rapper.bms

Unfortunately I couldn't just replace a single tm0 texture so I used the ```copy /b *.tm0 combined.bin``` command to append all the tm0 textures into a single binary file then ran this QuickBMS script (https://www.dropbox.com/s/pfvemwnw35dcjp3/parappa_2_compress.bms?dl=0)  to compress the file using the exact same compression algorithm the game uses and then ran an Hex comparison comparing the resulting compressed binary against the original INT file in which the textures where originally stored in, then filled the matched section with all zeroes.

![compare](https://cloud.githubusercontent.com/assets/7278372/6650706/a123d73a-c9dd-11e4-9a71-41d3589ee2a8.png)
![dummied_out](https://cloud.githubusercontent.com/assets/7278372/6650707/a48f0a02-c9dd-11e4-87b6-8a50d2ff8c93.png)


So basically I replaced _all_ the tm0 textures with zeroes inside each one of the INT archives... here are the ingame results.

**LOGO.INT**

Original
![logo2](https://cloud.githubusercontent.com/assets/7278372/6650684/36bf1d28-c9dd-11e4-8d1b-bd54aef3ff59.png)

Zeroed all tm0 textures
![logo](https://cloud.githubusercontent.com/assets/7278372/6650681/2e3d9774-c9dd-11e4-9015-c829847c5b56.png)


**ST01GM0.INT**
Original
![st01gm0_correct](https://cloud.githubusercontent.com/assets/7278372/6650692/5b261ef0-c9dd-11e4-96b7-5d4c2307da34.png)

Zeroed all tm0 textures
![st01gm0](https://cloud.githubusercontent.com/assets/7278372/6650694/67089b58-c9dd-11e4-874b-65b44922774a.png)


**INFO0.INT**
Original
![info0_correct](https://cloud.githubusercontent.com/assets/7278372/6650698/85a8054e-c9dd-11e4-8a57-daab0c982144.png)

Zeroed all tm0 textures
![info0](https://cloud.githubusercontent.com/assets/7278372/6650702/9a7811ee-c9dd-11e4-9a3b-13c376a8b3f0.png)


So it can be concluded that the game actually uses the .tm0 textures, so most likely they have different encoding.

**Comment by oddMLan** [comment]
Here is how the tm0 textures are viewed using Rainbow current release
NOTE: I changed the extension from tm0 to tm2 in order to make Rainbow able to open the whole folder.

These are APNG animations, if you don't see them animate, use Firefox or Chrome with [this extension](https://chrome.google.com/webstore/detail/apng/ehkepjiconegkhpodgoaeamnpckdbblp?hl=en)

**INFO0.INT tm0 textures**
![info0](https://cloud.githubusercontent.com/assets/7278372/6652795/a68f5b30-ca38-11e4-9a2a-6b9ccb92281b.png)

**LOGO.INT tm0 textures**
![logo](https://cloud.githubusercontent.com/assets/7278372/6652796/b8c5977e-ca38-11e4-9484-44b5baa03b09.png)

**ST01GM0.INT tm0 textures**
![st01gm0](https://cloud.githubusercontent.com/assets/7278372/6652800/c7621b86-ca38-11e4-84a4-2ea5cf49d62a.png)

**TITLE.INT tm0 textures**
![title](https://cloud.githubusercontent.com/assets/7278372/6652802/d69255e4-ca38-11e4-91d4-0396471550fb.png)

Oddly, some of the tm0 textures inside TITLE.INT can be seen correcty.
Maybe the TM0 textures have different bit depths?

**Comment by oddMLan** [comment]
Here are also some texture dumps I made using [Ninja Ripper](http://cgig.ru/ninjaripper/), which injects itself into the PCSX2 executable to dump all the DirectX 9 textures.

The textures are in BGR DDS format. To view the correct colors open them using [IrfanView](http://www.irfanview.com/) then go to Image -> Swap colors -> _RGB -> BGR_

[Normal textures](https://www.dropbox.com/s/jw325ye3gwyfuqf/PTR_normal_textures.rar?dl=0)
[Mostly zeroed textures](https://www.dropbox.com/s/gf3zdxonigt6dpr/PTR_zeroed_textures.rar?dl=0)

**Comment by marco-calautti** [comment]
Thank you for all the material and sorry for the late reply. Unfortunately this is a one-man project and My job is taking most of my time. I hope that once I get some free time, I'll be able to fix these issues. However, I am mostly confident that this game and many others, use a custom image encoding. This will need to retwrite an important part of Rainbow, which will allow to "plug" to a container format (like TIM2) a custom image encoder/decoder.
This will take some time, though.

**Comment by oddMLan** [comment]
Ok, I understand. Thanks for investing any little free time you have to this project.
Please let me know if you find anything interesting.

**Comment by oddMLan** [comment]
https://paste.ee/p/Txz5f
I extracted this strings from the ELF binary of the Parappa 2 McDonalds proto
Look up for all the TIM2 references, some weird Clut sizes, I see some mentions of mipmaps too.

**Comment by marco-calautti** [comment]
Sometime ago, I found this particular way of distributing pixels in a given image.
https://en.wikipedia.org/wiki/Z-order_curve

It seems that your images are encoded in this particular way. When I get enough time to implement the decoding algorithm, I'll make some tests on your tm0's.

Marco

**Comment by oddMLan** [comment]
That is so interesting (and weird). If that turns out to be it, I wonder why they would ever choose encoding their pictures that way. What advantages does it particularly offer?? Smaller files?
But, NanaOn-Sha DOES love interleaving their file formats.

**Comment by oddMLan** [comment]
Would this algorithm the same as texture swizzling?
https://fgiesen.wordpress.com/2011/01/17/texture-tiling-and-swizzling/

**Comment by exieln** [comment]
Sorry for a huge bump, but i'm wondering if macro has any progress done on the investigation of these files.

**Comment by marco-calautti** [comment]
I am sorry, but my job is taking much of my time now, and the spare free time I have, I prefer to spend it doing other stuff, like going out and enjoy my friends XD. Whenever I find a good period for working on Rainbow, I will investigate this special TIM0 format.

Anyway, everyone is free to submit a pull request, if something is discovered.

Marco

**Comment by oddMLan** [comment]
I think these .tm0 textures are sort of texture atlases for the 3D models, with varying bit depths. Very specific ones display fine in rainbow, but they are like, cut in chunks. Maybe the game takes all the tm0 files and assembles them in memory into a big sprite sheet. But to know for sure it requires to analyze the files themselves by someone who's knowledgable about the TIM2 file format

**Comment by oddMLan** [comment]
Closing this. @posesix wrote a decoder.

Textures are 4-bit swizzled into a 32-bit buffer. The CLUTs of various formats are combined with the 4-bit textures. However, the texture location info is not in the TM0, but in the .spm files, which is another odd format the game uses for its 3D models; they contain the TEX0 params and some VU instructions.

You can attempt to unswizzle the texture as whole, but it will be broken up and colorless (the cluts seem to be underneath, but no way to map them to the texture itself without the TEX0).
![imagen](https://user-images.githubusercontent.com/7278372/29642037-b937715e-8823-11e7-9f7d-63361a21afbe.png)

**Comment by TROguz** [comment]
Hi everyone. Would you help me?
I have translate group. We translated DMC3. And now we started translate DMC2.
Game has all text included textures.
So i need edit .biz textures and this textures is compressed.
Example files.
https://pixeldrain.com/u/wDoh5Rtj
