### ISSUE TITLE
Support DS/Wii formats?

### ISSUE THREAD

**Issue by PokeAcer** [marco-calautti/Rainbow#5]
The DS and Wii (and WiiU and 3DS) formats are widely supported along a ton of things, but hardly any have any good export function; it'd be really nice to have them in one place.

Wii TPLs (images) can be exported by wimgt (http://szs.wiimm.de) but it doesn't handle every format, and nobody does anything for the fonts either

**Comment by marco-calautti** [comment]
Apart from the C14X2 image format, Rainbow should be able to open and export to png most of TPL files. It is not clear to me if you are asking to implement something which is missing or just stating that Rainbow is able to open TPL files fine.
