### ISSUE TITLE
Error when exporting a image with Rainbow.

### ISSUE THREAD

**Issue by raulpuro** [marco-calautti/Rainbow#8]
Hi Marco,

   I have problems with some image files to export, I need to export modify the image and then re-insert.

  The images are displayed correctly in the application but once exported, it seems that they are not displayed correctly, well it is also likely that I am doing something wrong.

   Some images seem to contain several layers, I suppose it is a problem of difficult solution.

   I attached a file with some images that are showing wrongly and others that are displayed correctly with your application.

[Samples.zip](https://github.com/marco-calautti/Rainbow/files/1446052/Samples.zip)

Greetings and thanks for you time.

**Comment by marco-calautti** [comment]
I Raul, I tried to open some of the tm2 you attached. I am able to export and reimport them without issues. Furthermore, I just opened the exported pngs and they seem to be fine. What do you mean by "they are not displayed correctly"? Mind that such images have a transparent background, and then, they might be a bit tricky to visualize if you don't add some solid color background layer in your editing program. For example in photoshop or GIMP you can add a background layer filled with white or black, and you will be able to properly see the content of the png.

**Comment by marco-calautti** [comment]
If you talk about the multi-palette ones, then it is normal. For multi-palette TIM2, Rainbow exports a grayscale version of the image, and the it exports the palettes in separate pngs. In this case, you should edit only the grayscale version (unless you also want to edit the palettes.

**Comment by raulpuro** [comment]
It's true, you're right, sorry for bothering you but I was not able to see the images. Well I have to test what you indicate, putting a background layer to see the image and edit it.

I have to investigate because I think I would need to make the modifications of the image on the dark layer and I suppose that afterwards, remove the layer to be able to reimport.

This is complicated for me, I am a disaster with the editing of images but knowing that it is possible, it is only a matter of time that I find a way to do it.

Greetings and thanks for everything.

**Comment by marco-calautti** [comment]
On any decent graphics tool, you can add a layer without merging it to the original image. So you can see the final result without merging the two. Once you are done, just delete the background layer.

**Comment by marco-calautti** [comment]
@raulpuro Anyway, thanks to your TM2 files I found a bug on reimporting multi-palette TIM2 files. I added the new version in the release page. Please download it while it is fresh!
